# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Unit Test - Node.js ${{ matrix.node-name }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22, 24]
        include:
          - node-version: 20
            node-name: LTS-20
          - node-version: 22
            node-name: LTS-22
          - node-version: 24
            node-name: LTS-24

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm i --no-frozen-lockfile

      - name: Test
        run: pnpm test
